#%RAML 0.8
title: Customer API
version: 1.0
baseUri: http://localhost:8080/customer/{version}

schemas:
  - customer: !include customer.schema

resourceTypes:
  - collection:
      description: Collection of existing <<resourcePathName>>.
      get:
        description: |
          Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
      post:
        description: |
          Create a new <<resourcePathName|!singularize>>.
        queryParameters:
          accessToken:
            description: "The access token provided by the client."
            example: AABBCCDD
            required: true
            type: string
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<exampleItem>>
        responses:
          201:
            body:
              application/json:
                example: |
                  { "message": "The <<resourcePathName|!singularize>> has been succesfully created." }
          401:
            body:
              application/json:
                example: |
                  {"message": "Unauthorised."}
  - collection-item:
      description: Entity representing the <<resourcePathName|!singularize>>.
      get:
        description: |
          Get the <<resourcePathName|!singularize>> with <<resourcePathName|!singularize>>Id = {<<resourcePathName|!singularize>>Id}
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleItem>>
          404:
            body:
              application/json:
                example: |
                  {"message": "The <<resourcePathName|!singularize>> cannot be found." }
      put:
        description: |
          Updates an existing <<resourcePathName|!singularize>>.
        queryParameters:
          accessToken:
            description: "The access token provided by the client."
            example: AABBCCDD
            required: true
            type: string
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<exampleItem>>
        responses:
          201:
            body:
              application/json:
                example: |
                  { "message": "The <<resourcePathName|!singularize>> has been succesfully updated." }
          401:
            body:
              application/json:
                example: |
                  {"message": "Unauthorised."}
      delete:
        description: |
          Deletes an existing <<resourcePathName|!singularize>>.
        queryParameters:
          accessToken:
            description: "The access token provided by the client"
            example: AABBCCDD
            required: true
            type: string
        responses:
          201:
            body:
              application/json:
                example: |
                  { "message": "The <<resourcePathName|!singularize>> has been succesfully deleted." }
          401:
            body:
              application/json:
                example: |
                  {"message": "Unauthorised."}
/customers:
  type: 
    collection:
      exampleCollection: !include customer-get.sample
      exampleItem: !include customer-new.sample
  /{customerId}:
    type: 
      collection-item:
        exampleItem: !include customer-update.sample

#/orders:
#  type: 
#    collection:
#      exampleCollection: |
#        {}
#      exampleItem: |
#        {}
#  /{orderId}:
#    type: 
#      collection-item:
#        exampleItem: |
#          {}
          
#/products:
#  type: 
#    collection:
#      exampleCollection: |
#        {}
#      exampleItem: |
#        {}
#  /{productId}:
#    type: 
#      collection-item:
#        exampleItem: |
#          {} 
